name: Test

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -e . pytest mypy
      - run: mypy .
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: |
          python -m venv env
          source env/bin/activate
          pip install -e . pytest
          pytest
